name: CustomBosses
description: Adds custom bosses
author: RypoFalem
version: 0.1
main: io.github.rypofalem.bigbads.BigBadsPlugin
depend: [ Custom ]
commands:
permissions:
  boss.admin:
    description: admin stuff
    default: OP